function gx = g_nsess(x,P,u,in)
gx = zeros(in.dim.p,1);
for i=1:in.nsess
gi = feval(...
        in.sess(i).g_fname,...
        x(in.sess(i).ind.x),...
        P(in.sess(i).ind.phi),...
        u(in.sess(i).ind.u),...
        in.sess(i).inG);
    gx(in.sess(i).ind.gx,1) = gi;
end

