function [Co] = dcm_plot_reorderedCov(C,nreg,u,ha)

try; u; catch; u = []; end

try
    set(ha,'nextplot','add');
catch
    hf = figure('color',[1 1 1]);
    ha = axes('parent',hf,'nextplot','add');
end


nc = size(C,1);
nt = nc./nreg;
reorder = [];
tick = [];
xtl = cell(nreg,1);
for i=1:nreg
    roi{i} = i:nreg:nc;
    reorder = [reorder,roi{i}];
    if i<nreg
        tick = [tick;i*nt+0.5];
    end
    xtl{i} = ['node ',num2str(i)];
end


Co = C(reorder,reorder);
imagesc(Co,'parent',ha)
for i=1:nreg-1
    plot(ha,...
        [0.5,nc+0.5],...
        [tick(i),tick(i)],...
        'color',[1 1 1])
    plot(ha,...
        [tick(i),tick(i)],...
        [0.5 nc+0.5],...
        'color',[1 1 1])
end

xt = 0:nt:nt*(nreg-1);
xt = xt+ nt/2;

axis(ha,'square')
set(ha,...
    'xlim',[0.5,nc+0.5],...
    'ylim',[0.5,nc+0.5],...
    'xtick',xt,...
    'xticklabel',xtl,...
    'ytick',xt,...
    'yticklabel',xtl,...
    'ydir','reverse')
colorbar('peer',ha)


if ~isempty(u) && size(u,2)>=nt
    
    u = u(:,1:nt);
    su = ~~sum(u,1);
    ind = [find(diff(su)==-1)+1,nt];
    ind2 = find(diff(su)==1)+1;
    
    for i=1:length(ind2)
        
        plot(ha,...
            [ind2(i)+0.5,ind2(i)+0.5],...
            [ind2(i)+0.5,ind(i)+0.5],...
            'color',[0 0 0])
        plot(ha,...
            [ind(i)+0.5,ind(i)+0.5],...
            [ind2(i)+0.5,ind(i)+0.5],...
            'color',[0 0 0])
        plot(ha,...
            [ind(i)+0.5,ind2(i)+0.5],...
            [ind2(i)+0.5,ind2(i)+0.5],...
            'color',[0 0 0])
        plot(ha,...
            [ind(i)+0.5,ind2(i)+0.5],...
            [ind(i)+0.5,ind(i)+0.5],...
            'color',[0 0 0])

    end
    
    
end
    


%
%
%
%
%
%
% plot(ha(3),...
%     [ind2(1)+1.5 ind2(1)+1.5],...
%     [2*between-ind2(1)-0.5 2*between-ind(1)+-.5],...
%     'color',[0 0 0])
% plot(ha(3),...
%     [ind(1)+1.5 ind(1)+1.5],...
%     [2*between-ind2(1)-0.5 2*between-ind(1)-0.5],...
%     'color',[0 0 0])
% plot(ha(3),...
%     [ind(1)+1.5 ind2(1)+1.5],...
%     [2*between-ind2(1)-0.5 2*between-ind2(1)-0.5],...
%     'color',[0 0 0])
% plot(ha(3),...
%     [ind(1)+1.5 ind2(1)+1.5],...
%     [2*between-ind(1)-0.5 2*between-ind(1)-0.5],...
%     'color',[0 0 0])
% axis(ha(3),'square')
% set(ha(3),...
%     'xlim',[0.5,between.*2+0.5],...
%     'ylim',[0.5,between.*2+0.5],...
%     'xtick',[between/2,3*between/2],...
%     'xticklabel',{'node 2','node 1'},...
%     'ytick',[between/2,3*between/2],...
%     'yticklabel',{'node 2','node 1'})
% colorbar('peer',ha(3))